/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.CollectionNames;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author caue_
 */
public class InicialFrame extends javax.swing.JFrame {

    /**
     * Creates new form InicialFrame
     */
    public CollectionNames cn=new CollectionNames();
    
    public InicialFrame() {
        initComponents();
        
        btInformation.setBackground(new Color(0,0,0,0));
        fieldNickName.setBackground(new Color(255,255,255,10));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        btLogin = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        btInformation = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        fieldNickName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chapryt - Inicial Frame");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        backgroundPanel.setBackground(new java.awt.Color(0, 0, 0));
        backgroundPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backgroundPanel.setLayout(null);

        btLogin.setBackground(new java.awt.Color(0, 0, 0));
        btLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btLogin.setForeground(new java.awt.Color(255, 255, 255));
        btLogin.setText("Login");
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        backgroundPanel.add(btLogin);
        btLogin.setBounds(100, 190, 210, 34);

        btExit.setBackground(new java.awt.Color(0, 0, 0));
        btExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btExit.setForeground(new java.awt.Color(255, 255, 255));
        btExit.setText("Exit");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });
        backgroundPanel.add(btExit);
        btExit.setBounds(150, 230, 110, 34);

        btInformation.setBackground(new java.awt.Color(46, 46, 46));
        btInformation.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btInformation.setForeground(new java.awt.Color(255, 255, 255));
        btInformation.setText("Information");
        btInformation.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btInformation.setFocusCycleRoot(true);
        btInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInformationActionPerformed(evt);
            }
        });
        backgroundPanel.add(btInformation);
        btInformation.setBounds(290, 10, 105, 17);

        title.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Chapryt");
        backgroundPanel.add(title);
        title.setBounds(0, 20, 400, 49);

        labelUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelUser.setForeground(new java.awt.Color(255, 255, 255));
        labelUser.setText("Nickname:");
        backgroundPanel.add(labelUser);
        labelUser.setBounds(26, 130, 100, 30);

        fieldNickName.setBackground(new java.awt.Color(51, 51, 51));
        fieldNickName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fieldNickName.setForeground(new java.awt.Color(254, 254, 254));
        fieldNickName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        backgroundPanel.add(fieldNickName);
        fieldNickName.setBounds(130, 130, 240, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fill the field with a user name:");
        backgroundPanel.add(jLabel1);
        jLabel1.setBounds(0, 90, 400, 20);

        getContentPane().add(backgroundPanel);

        setSize(new java.awt.Dimension(418, 323));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_btLoginActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        // TODO add your handling code here:
        int x=JOptionPane.showConfirmDialog(null, "Do you really want to close the Chator?", "Message", JOptionPane.YES_NO_OPTION);
        if(x==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btExitActionPerformed

    private void btInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInformationActionPerformed
        // TODO add your handling code here:
        InformationFrame inf=new InformationFrame();
        this.dispose();
        inf.setVisible(true);
    }//GEN-LAST:event_btInformationActionPerformed

    public void login(){
        boolean opt=cn.login(fieldNickName.getText());
        if(opt){
            UserChatFrame ucf=new UserChatFrame();
            this.dispose();
            ucf.initUserChat(fieldNickName.getText());
        }
    }
    
    public void cleanIF(){
        fieldNickName.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicialFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicialFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicialFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicialFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicialFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btInformation;
    private javax.swing.JButton btLogin;
    private javax.swing.JTextField fieldNickName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelUser;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
