/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.CollectionNames;
import javax.swing.JOptionPane;

/**
 *
 * @author caue
 */
public class UserChatFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserChatFrame
     */
    public UserChatFrame() {
        initComponents();
    }
    
    private String nickname;
    private CollectionNames cn=new CollectionNames();
    private UserChat uc=new UserChat();
    
    public void initUserChat(String nickname){
        this.nickname=nickname;
        userLabel.setText("User: "+nickname);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        titlefrae = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        btLogout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btOpenChat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chapryt - User List");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        backgroundPanel.setBackground(new java.awt.Color(0, 0, 0));
        backgroundPanel.setLayout(null);

        titlefrae.setBackground(new java.awt.Color(1, 1, 1));
        titlefrae.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        titlefrae.setForeground(new java.awt.Color(254, 254, 254));
        titlefrae.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlefrae.setText("Chapryt");
        backgroundPanel.add(titlefrae);
        titlefrae.setBounds(0, 0, 320, 70);

        userLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        userLabel.setForeground(new java.awt.Color(254, 254, 254));
        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userLabel.setText("User:");
        backgroundPanel.add(userLabel);
        userLabel.setBounds(0, 80, 320, 30);

        btLogout.setBackground(new java.awt.Color(0, 0, 0));
        btLogout.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btLogout.setForeground(new java.awt.Color(254, 254, 254));
        btLogout.setText("Logout");
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoutActionPerformed(evt);
            }
        });
        backgroundPanel.add(btLogout);
        btLogout.setBounds(30, 440, 260, 34);

        jList1.setBackground(new java.awt.Color(38, 38, 38));
        jList1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 254, 254), 1, true));
        jList1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jList1.setForeground(new java.awt.Color(254, 254, 254));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Maria", "João", "Pedro", "Joana", "Roberto", "Carlos", "Vitória", "Gabriela", "José", "Marcos", "Josefa", "Creusa", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jList1.setSelectionForeground(new java.awt.Color(38, 38, 38));
        jScrollPane1.setViewportView(jList1);

        backgroundPanel.add(jScrollPane1);
        jScrollPane1.setBounds(30, 170, 260, 200);

        btOpenChat.setBackground(new java.awt.Color(0, 0, 0));
        btOpenChat.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btOpenChat.setForeground(new java.awt.Color(254, 254, 254));
        btOpenChat.setText("Open Chat");
        btOpenChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOpenChatActionPerformed(evt);
            }
        });
        backgroundPanel.add(btOpenChat);
        btOpenChat.setBounds(30, 390, 260, 34);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("List os User in Chapryt:");
        backgroundPanel.add(jLabel1);
        jLabel1.setBounds(0, 130, 320, 20);

        getContentPane().add(backgroundPanel);

        setSize(new java.awt.Dimension(335, 542));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoutActionPerformed
        // TODO add your handling code here:
        int x=JOptionPane.showConfirmDialog(null, "Do you really want to logout?", "Message", JOptionPane.YES_NO_OPTION);
        if(x==JOptionPane.YES_OPTION){
            logout();
        }
    }//GEN-LAST:event_btLogoutActionPerformed

    private void btOpenChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOpenChatActionPerformed
        // TODO add your handling code here:
        openChat();
    }//GEN-LAST:event_btOpenChatActionPerformed

    public void openChat(){
        uc.setVisible(true);
    }
    
    public void logout(){
        InicialFrame inf=new InicialFrame();
        cn.delName(nickname);
        uc.dispose();
        this.dispose();
        inf.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserChatFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton btLogout;
    private javax.swing.JButton btOpenChat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel titlefrae;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
